namespace MyCondo.Application.Features.Expenses.Expenses.DTOs;

public sealed record ExpenseDto(
    Guid ExpenseId,
    Guid? BuildingId,
    string? BuildingName,
    Guid ExpenseTypeId,
    string ExpenseTypeName,
    Guid? ExpenseCategoryId,
    string? ExpenseCategoryName,
    Guid? FundId,
    string? FundName,
    DateOnly ExpenseDate,
    DateOnly AccountingDate,
    string Description,
    string? Payee,
    string? ReferenceNumber,
    decimal Amount,
    bool IsPaid,
    string PaymentMethod,
    string? Notes,
    string Status,
    string? VoidReason,
    Guid? FinancialAccountId,
    Guid? PostingId,
    Guid? PaymentPostingId,
    Guid? ReversalPostingId,
    Guid? PaymentReversalPostingId,
    Guid? CreatedBy,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? UpdatedAtUtc
);
